### ISSUE TITLE
Panicking at core client due to failed stream

### ISSUE THREAD

**Issue by saberistic** [GenesysGo/dagger-testnet-issues#11]
**Describe the bug**
When running service it posts a panick error that I am not sure what's it for

```
dagger@pop-os:~$ sudo systemctl restart wield.service
[sudo] password for dagger: 
dagger@pop-os:~$ tail -f config.log            
2024-01-06T12:44:24.355423496-06:00 [INFO] dagger::p2p::join - Initialized endpoint
2024-01-06T12:44:24.355466006-06:00 [INFO] dagger::db::peers - Attempting to open existing rocksdb for peers
2024-01-06T12:44:34.517173091-06:00 [WARN] dagger_logger::metrics - run: submit status: 204
2024-01-06T12:45:24.510735525-06:00 [WARN] dagger::p2p::join - received invalid response for bundlehash from 184.154.98.116:2030, trying next node
2024-01-06T12:45:59.550393786-06:00 [INFO] dagger_logger::metrics - datapoint: user_cpu_metrics num_logical_cpu_processors=16 cpu_speed=400 ram=65689416 total_storage_space=979188154 cpu_model="12th Gen Intel(R) Core(TM) i5-1240P" wield_version="0.7.1" node_id="AWBxXYiPCSaz8uUCaoeVhHbgsRQZetVuTBKKuNLX3tGE"
2024-01-06T12:45:59.551430994-06:00 [INFO] dagger::p2p::join - Obtained join config: JoinConfig { trusted_nodes: Some([184.154.98.116:2030, 184.154.98.117:2030, 184.154.98.118:2030, 184.154.98.119:2030, 184.154.98.120:2030]), node_config: NodeConfig { socket: 2030, keypair_file: "id.json" }, storage: StorageConfig { peers_db: "/mnt/dag/dbs/peers.db" }, genesis: None, dagger: JoinAndRetrieve } 
2024-01-06T12:45:59.552184148-06:00 [INFO] dagger::p2p::join - Joining network as AWBxXYiPCSaz8uUCaoeVhHbgsRQZetVuTBKKuNLX3tGE on 10.96.0.22
2024-01-06T12:45:59.554237536-06:00 [INFO] dagger::p2p::join - Initialized endpoint
2024-01-06T12:45:59.554297333-06:00 [INFO] dagger::db::peers - Creating new rocksdb for peers
2024-01-06T12:46:04.719533025-06:00 [WARN] dagger_logger::metrics - run: submit status: 204
2024-01-06T12:46:59.868360732-06:00 [ERROR] log_panics - thread 'dagger-toplevel' panicked at 'failed to join network: Daggerp2pError { err: FailedToOpenStream }': core/src/client.rs:605
2024-01-06T12:46:59.868658640-06:00 [ERROR] log_panics - thread 'main' panicked at 'shouldn't fail to recv Comms : RecvError(())': core/src/client.rs:626
2024-01-06T12:47:19.368102524-06:00 [INFO] dagger_logger::metrics - datapoint: user_cpu_metrics num_logical_cpu_processors=16 cpu_speed=816 ram=65689416 total_storage_space=979188154 cpu
_model="12th Gen Intel(R) Core(TM) i5-1240P" wield_version="0.7.1" node_id="AWBxXYiPCSaz8uUCa
oeVhHbgsRQZetVuTBKKuNLX3tGE"
2024-01-06T12:47:19.368872289-06:00 [INFO] dagger::p2p::join - Obtained join config: JoinConf
ig { trusted_nodes: Some([184.154.98.116:2030, 184.154.98.117:2030, 184.154.98.118:2030, 184.
154.98.119:2030, 184.154.98.120:2030]), node_config: NodeConfig { socket: 2030, keypair_file:
 "id.json" }, storage: StorageConfig { peers_db: "/mnt/dag/dbs/peers.db" }, genesis: None, da
gger: JoinAndRetrieve } 
2024-01-06T12:47:19.369790858-06:00 [INFO] dagger::p2p::join - Joining network as AWBxXYiPCSa
z8uUCaoeVhHbgsRQZetVuTBKKuNLX3tGE on 10.96.0.22
2024-01-06T12:47:19.372252191-06:00 [INFO] dagger::p2p::join - Initialized endpoint
2024-01-06T12:47:19.372311578-06:00 [INFO] dagger::db::peers - Attempting to open existing ro
cksdb for peers
2024-01-06T12:47:24.536373261-06:00 [WARN] dagger_logger::metrics - run: submit status: 204
```
And then it stops there with no further logs

**To Reproduce**
I am not sure how to reproduce it. happened on a linux debian based. I have connected a external storage, gave access to disk, I see directories are made

**Comment by tracy-codes** [comment]
It looks like your node may be behind a VPC, Firewall, NAT, or something else where its main network interface IP address is `10.96.0.22` is a private IP address. You need to figure out how to expose your server to the public internet is some way. Some users in our discord server have setups similar to this, and have figured out exposing their network publicly. I'd suggest asking there for further support.
