### ISSUE TITLE
Wield Node crashed. Panics from wield-metrics-agent, thread 'comms' thread 'controller' thread 'unnamed'.

### ISSUE THREAD

**Issue by Kriptikz** [GenesysGo/dagger-testnet-issues#39]
**Describe the bug**
Wield Node Version: 0.8.1
VPS: Linode
Node ID: AzrAW1uLjrV9nuDZyCD1nmoRovbyPyXWYWQ12goZedhn
Location: US Chicago

Wield node crashed and required a manual restart to get it going again. Log file grew over 10GB in a few hours, over 30 million lines of :

```
2024-02-02T08:49:21.240033429+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
```

All of the logs look normal overall. Looks like the issue occurred here.
```
2024-02-02T08:47:19.211195583+00:00 [INFO] dagger::p2p::graph::dagger - bundle 77914 finalized!
2024-02-02T08:47:19.211445779+00:00 [INFO] dagger_logger::metrics - datapoint: new_ordered_events new_ordered_events=5
2024-02-02T08:47:19.211476720+00:00 [INFO] dagger_logger::metrics - datapoint: executed_block block_transactions_count=6 block_execution_lapsed_us=15
2024-02-02T08:47:19.211485350+00:00 [INFO] dagger_logger::metrics - datapoint: executed_block block_transactions_count=3 block_execution_lapsed_us=8
2024-02-02T08:47:19.211491900+00:00 [INFO] dagger_logger::metrics - datapoint: executed_block block_transactions_count=6 block_execution_lapsed_us=13
2024-02-02T08:47:19.211508210+00:00 [INFO] dagger_logger::metrics - datapoint: executed_block block_transactions_count=6 block_execution_lapsed_us=10
2024-02-02T08:47:19.211515600+00:00 [INFO] dagger_logger::metrics - datapoint: executed_block block_transactions_count=6 block_execution_lapsed_us=10
2024-02-02T08:47:19.211521490+00:00 [INFO] dagger_logger::metrics - datapoint: new_bundlehash new_transaction_count=2735061 bundlehash="EVssyEXDfmRaCtkZCVCFR64jkkZgypC5NmuQf6hmKa6m"
2024-02-02T08:47:20.005214898+00:00 [INFO] dagger::p2p::graph::dagger - bundle 77915 finalized!
2024-02-02T08:47:20.005298670+00:00 [INFO] dagger_logger::metrics - datapoint: new_ordered_events new_ordered_events=10
2024-02-02T08:47:20.006049236+00:00 [ERROR] log_panics - thread 'wield-metrics-agent' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Os { code: 24, kind: Uncategorized, message: "Too many open files" } }': /.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.22/src/blocking/client.rs:877
2024-02-02T08:47:20.406314160+00:00 [INFO] dagger::p2p::graph::dagger - bundle 77916 finalized!
2024-02-02T08:47:20.406365991+00:00 [ERROR] log_panics - thread 'controller' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"': dagger-logger/src/metrics.rs:439
2024-02-02T08:47:20.418672749+00:00 [ERROR] log_panics - thread 'comms' panicked at 'controller will not drop receiver: SendError { .. }': core/src/p2p/message/handlers/client.rs:434
2024-02-02T08:47:20.804390325+00:00 [ERROR] log_panics - thread 'comms' panicked at 'controller will not drop receiver: SendError { .. }': core/src/p2p/message/handlers/client.rs:434
2024-02-02T08:47:22.873956628+00:00 [ERROR] log_panics - thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"': dagger-logger/src/metrics.rs:439
2024-02-02T08:48:20.419993517+00:00 [WARN] dagger::client - received invalid response for bundlehash from 172.234.16.217:2030
2024-02-02T08:48:20.420099359+00:00 [WARN] dagger::client - Long sync with peer 6uFd3N1H3bd7XA2bsRRFXYqTqMKY6MPzxdpocS36eDa6: 60006 millis
2024-02-02T08:48:20.805248839+00:00 [WARN] dagger::client - received invalid response for bundlehash from 172.234.16.217:2030
2024-02-02T08:48:20.805292820+00:00 [WARN] dagger::client - Long sync with peer Cb1CwnBppUWfNZmeZfJoVdVzsbrJXkTHN7Fk64Q82dwy: 60009 millis
2024-02-02T08:48:20.838514458+00:00 [ERROR] log_panics - thread 'comms' panicked at 'controller will not drop receiver: SendError { .. }': core/src/p2p/message/handlers/client.rs:434
2024-02-02T08:48:21.224258051+00:00 [ERROR] log_panics - thread 'comms' panicked at 'controller will not drop receiver: SendError { .. }': core/src/p2p/message/handlers/client.rs:434
2024-02-02T08:49:20.839479417+00:00 [WARN] dagger::client - received invalid response for bundlehash from 172.234.16.217:2030
2024-02-02T08:49:20.839618470+00:00 [WARN] dagger::client - Long sync with peer ARfg7k3wTR43W9pqNhNVsSAvazDfvXyNNNVyKjn4GwaN: 60018 millis
2024-02-02T08:49:20.880875007+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2200 w/ current nodes 2200
2024-02-02T08:49:20.926227463+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2300 w/ current nodes 2300
2024-02-02T08:49:20.956509068+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2400 w/ current nodes 2400
2024-02-02T08:49:20.983243746+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2500 w/ current nodes 2500
2024-02-02T08:49:21.005679539+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2600 w/ current nodes 2600
2024-02-02T08:49:21.028221934+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2700 w/ current nodes 2700
2024-02-02T08:49:21.048649483+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2800 w/ current nodes 2800
2024-02-02T08:49:21.068766905+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 2900 w/ current nodes 2900
2024-02-02T08:49:21.090633336+00:00 [INFO] dagger::p2p::graph::dagger - Added node to DAGGER in 0 millis; new size is 3000 w/ current nodes 3000
2024-02-02T08:49:21.179991399+00:00 [INFO] dagger::p2p::graph::dagger - bundle 77917 finalized!
2024-02-02T08:49:21.180030720+00:00 [ERROR] log_panics - thread 'dagger-toplevel' panicked at 'graph -> controller bundle sender panic: SendError { .. }': core/src/p2p/graph/dagger.rs:2127
2024-02-02T08:49:21.186244157+00:00 [ERROR] log_panics - thread '<unnamed>' panicked at 'graph module should never drop sender: RecvError': core/src/p2p/graph/dagger.rs:4184
2024-02-02T08:49:21.240033429+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
```

I've included the first ~1million lines of logs in the log file, should be all you need as the rest is just the same error spammed for over 30 millions lines.

[log file download from shdwdrive](https://shdw-drive.genesysgo.net/8o1BAVGL5NAeFxhyrprERJqRco2rjcJvqBtPFjFqL8vD/2024_02_02.log)

**Comment by tracy-codes** [comment]
Thank you for reporting this. Can you please provide the following information:

1. your node's ID
2. what server hosting provider you're using (if using one, if not, just say residential or if its collocated in a datacenter please provide the datacenter information)
3. geographic location of your node

**Comment by Kriptikz** [comment]
Updated post with more info like node id, etc. 

Looks like main culprit could be this error:
```
2024-02-02T08:47:20.006049236+00:00 [ERROR] log_panics - thread 'wield-metrics-agent' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Os { code: 24, kind: Uncategorized, message: "Too many open files" } }': /.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.22/src/blocking/client.rs:877
```

Here is my ulimit info to verify it is correct.

<img width="869" alt="Screenshot 2024-02-03 at 8 24 01 AM" src="https://github.com/GenesysGo/dagger-testnet-issues/assets/17520593/32199978-7be1-4ec2-92cb-af8cb7dd518b">
