### ISSUE TITLE
Failed to connect to trusted peer 165.232.137.22:2030: failed to connect to peer

### ISSUE THREAD

**Issue by cybotx1024** [GenesysGo/dagger-testnet-issues#5]
I shut down the node during epoch 167 to do some hardware maintenance using option 6 on the wield-installer.sh script, after the restart the node would not reconnect and kept giving errors captured in the log below. I left it for over 9 hours but would still give the same error.
![Screenshot at 2023-12-24 09-20-32](https://github.com/GenesysGo/dagger-testnet-issues/assets/12415566/2657f19e-0f15-45f0-a6c0-4309ebea8e01)
I tried removing the 165.232.137.22 IP from trusted peers to see if it would reconnect without it but it  stopped at:
`2023-12-24T20:03:31.381257790+00:00 [WARN] dagger_logger::metrics - run: submit status: 204`

I  have attached the log file captured after removing the IP
[config.log](https://github.com/GenesysGo/dagger-testnet-issues/files/13762841/config.log)

**Comment by cybotx1024** [comment]
if i start the node and leave it to retry i get the config.log filled with these logs. In a few hours the log file grows to 300+GB

`2023-12-25T12:16:34.382884680+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.382899403+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.382915429+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.382928458+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.382943175+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.382959504+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.382972968+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.382989617+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383003396+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383017195+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383031300+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383045797+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383060902+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383075189+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383089284+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383102285+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383117100+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383131021+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383144337+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383158575+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383173006+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383186482+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383207357+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383222+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383235433+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383250529+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383266580+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383279722+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383294401+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383308151+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383321862+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383335747+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383350112+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383363540+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383378167+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383392512+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383405477+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383419411+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383433677+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383451043+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383465368+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383479550+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383492525+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383508226+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383521881+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383861689+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383878508+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383892045+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383907184+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383921395+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383933165+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383946910+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383960875+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383974836+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.383989202+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384003638+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384021364+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384035918+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384050588+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384063736+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384079791+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384093438+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384105568+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384119312+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384133333+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384147061+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384161343+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384175829+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384189092+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384203901+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384218517+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384231664+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384245634+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384263738+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384277387+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384291349+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384305646+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384319064+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384333865+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384347400+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384361314+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384375713+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384389930+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384402754+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384417467+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384431373+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384445204+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384459035+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384473754+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384486851+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384505924+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384519261+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }
2023-12-25T12:16:34.384856663+00:00 [ERROR] dagger_p2p - failed connect Unspecified { source: Location { file: "/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s2n-quic-transport-0.31.0/src/endpoint/connect.rs", line: 148, col: 40 } }`

**Comment by cybotx1024** [comment]
it looks like the node starts to connect and sync with the network then gets the following warnings and errors:

`2023-12-25T14:40:32.867389601+00:00 [WARN] dagger::p2p::graph::dagger - digest time: 591394 millis; new_events = 44355; prev events 0; unordered_events = 2492
2023-12-25T14:40:32.867434585+00:00 [ERROR] log_panics - thread 'dagger-toplevel' panicked at 'Should not be genesis event': core/src/p2p/graph/dagger.rs:710
2023-12-25T14:40:32.889088319+00:00 [ERROR] log_panics - thread '<unnamed>' panicked at 'graph module should never drop sender: RecvError': core/src/p2p/graph/dagger.rs:2609`

the last few lines of the attached log repeat till it baloons to several gigabytes in size
[config.log](https://github.com/GenesysGo/dagger-testnet-issues/files/13766781/config.log)

**Comment by Lazydayz137** [comment]
Most issues seem related yet no courtesy to address it, even when It was ongoing when post to post here was made, if memory serves.

**Comment by tracy-codes** [comment]
The two specific problems mentioned in this issue have been resolved with recent updates.
