### ISSUE TITLE
Failed to create rocksDb dir

### ISSUE THREAD

**Issue by RamanSB** [GenesysGo/dagger-testnet-issues#55]
**Describe the bug**
2024-02-11T20:12:04.931373490+01:00 [INFO] dagger::db::peers - Attempting to open existing rocksdb for peers
**2024-02-11T20:12:04.973625407+01:00 [ERROR] log_panics - thread 'dagger-toplevel' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "Failed to create RocksDB directory: `Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }`." }': core/src/p2p/join.rs:215
2024-02-11T20:12:04.977385203+01:00 [ERROR] log_panics - thread 'main' panicked at 'shouldn't fail to recv Comms : RecvError(())': core/src/client.rs:759**

Using a Contabo Node. 
Node ID: FzZN7xa1oHULZpAtmpzTvCLv34194H2CTg9rfAnDmSgh

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RamanSB** [comment]
Permissions issue.
